a = input('Digite algo: ')
print(f'O tipo primitivo de {a} é ', type(a))
print('Só tem espaços?', a.isspace())
print('É numérico?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('É maiúsculo?', a.isupper())
print('É minúsculo?', a.islower())
print('É capitalizado?', a.istitle())