from time import sleep
a= int(input('Type a distance in meters(only number): '))
print('Converting...')
sleep(1)
print('.')
sleep(1)
print('.')
sleep(1)
print('.')
sleep(1)
print('.')
print(f'The measure typed corresponds to:\n{a/1000}km\n{a/100}hm\n{a/10}dam\n{a*10}dm\n{a*100}cm\n{a*1000}mm')
